Traceback (most recent call last):
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
from scipy import stats

%matplotlib inline
from matplotlib import pyplot as plt

from image_sim import dark_current, read_noise

------------------

[31m---------------------------------------------------------------------------[39m
[31mImportError[39m                               Traceback (most recent call last)
[36mCell[39m[36m [39m[32mIn[1][39m[32m, line 7[39m
[32m      4[39m get_ipython().run_line_magic([33m'[39m[33mmatplotlib[39m[33m'[39m, [33m'[39m[33minline[39m[33m'[39m)
[32m      5[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mmatplotlib[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m pyplot [38;5;28;01mas[39;00m plt
[32m----> [39m[32m7[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mimage_sim[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m dark_current, read_noise

[36mFile [39m[32m~/work/ccd-reduction-and-photometry-guide/ccd-reduction-and-photometry-guide/notebooks/image_sim.py:6[39m
[32m      3[39m [38;5;28;01mimport[39;00m[38;5;250m [39m[34;01mnumpy[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[34;01mnp[39;00m
[32m      5[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mastropy[39;00m[34;01m.[39;00m[34;01mmodeling[39;00m[34;01m.[39;00m[34;01mmodels[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m Gaussian2D, RickerWavelet2D, Const2D
[32m----> [39m[32m6[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mphotutils[39;00m[34;01m.[39;00m[34;01mdatasets[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m (make_random_gaussians_table,
[32m      7[39m                                 make_gaussian_sources_image)
[32m      8[39m [38;5;28;01mfrom[39;00m[38;5;250m [39m[34;01mphotutils[39;00m[34;01m.[39;00m[34;01maperture[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m EllipticalAperture
[32m     10[39m [38;5;66;03m# To use a seed, set it in the environment. Useful for minimizing changes when[39;00m
[32m     11[39m [38;5;66;03m# publishing the book.[39;00m

[31mImportError[39m: cannot import name 'make_random_gaussians_table' from 'photutils.datasets' (/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/photutils/datasets/__init__.py)
ImportError: cannot import name 'make_random_gaussians_table' from 'photutils.datasets' (/home/runner/miniconda3/envs/mamba/lib/python3.11/site-packages/photutils/datasets/__init__.py)

